### ISSUE TITLE
shell_options is not defined

### ISSUE THREAD

**Issue by Cinemacloud** [sinclairzx81/smoke#4]
Installed smoke, then npm install, npm run bench but I get this error:
shell_options is not defined

I didn't notice anything in docs about what this means or needs to work out of the box.

**Comment by sinclairzx81** [comment]
Hi, Sorry for the delay in response. (In reference to https://github.com/sinclairzx81/smoke/issues/3)

Since I last did work on this project, a lot of the build tooling used to build it has been overhauled. The `shell_options(...)` is a relic of a previous version of the [`smoke-task`](https://www.npmjs.com/package/smoke-task) module that is used to automate build and watch | reload cycles (the code you see in that task.js file). Unfortunately, this library hasn't been updated to reflect these changes.

However, the plan for this project is to move the local build tooling over to the [`parcel`](https://parceljs.org/) bundler which should help reduce the amount of complexity on local builds. Note, I could use some help with this if you're interested.

If you just want to build the `smoke-node` package, I've just made a quick update to the project, so clone the project locally, and run the following which will build the `smoke-node` client libraries that you can reference in your own project.

```bash
# ensure you have typescript installed
$ npm install typescript@latest -g

# build the smoke-node package from the project root.
$ tsc -p ./packages/smoke-node/src/tsconfig.json --outDir ./build
```
Alternatively, you may be able to just copy the `./packages/smoke-node/src` directory into your local project and use your existing build tooling to build it (i.e, WebPack, Rollup, Parcel, etc)

I won't have time to look at redoing the build tooling for some time (at least a month), so i hope this information helps you get going, additionally, you can check [here](https://repl.it/@sinclairzx81/smoke) for a public signalling hub to use and test with. (Which is a public implementation of `./packages/smoke-hub`.)

Good Luck!

**Comment by Cinemacloud** [comment]
Thanks for trying to explain though I am not sure how the two commits you just made fix 'npm run bench' from using shell_options. Or did I misunderstand what you meant? 

Can I just comment out the shell_options line from tasks or is there a workaround, is that what tsc line achieves? And is there a more modern smoke-tasks I can use? Seems that repo hasn't been updated in 6 months. 

I'd be glad to help, if I can, to migrate it.

Peter

**Comment by sinclairzx81** [comment]
Hi,

Unfortunately, just commenting out the `shell_options` won't work. The tooling has changed quite a bit. To try help you out a bit, I have setup a new branch using Parcel which should let you build and test locally. You can view it [here](https://github.com/sinclairzx81/smoke/tree/smoke-next).

```bash
$ git clone https://github.com/sinclairzx81/smoke.git
$ git checkout smoke-next
$ npm install
$ npm run watch
```
Move your code into that `bench` project and see how you go. Note that the 'next' branch is missing all the tests and documentation generators, but should give you a nice enough scripting environment to do your work. (Can't really comment on the MSE issue at this time, would need to dig into it).

Let me know how you go.

**Comment by Cinemacloud** [comment]
Sweet that watched. I tried copying the example for media extensions to the bench/index.ts of smoke-next and I got some address errors. Do you think you could show me an example from https://github.com/sinclairzx81/smoke/tree/master/packages/smoke-node#Example1 which works on smoke-next?

**Comment by sinclairzx81** [comment]
I've pushed a small update with a media proxy example. The database and bucket examples should work as per documentation, but the media stream is a bit more involved.

```
$ git pull origin smoke-next
$ npm run clean
$ npm run watch
```
Examples
```
http://localhost:5000/index.html # Original Node example.
http://localhost:5000/media.html # Media Proxy example.
```
Note: you may have to visit the .html files explicitly, I'm tracking an issue over [here](https://github.com/parcel-bundler/parcel/issues/4213) with respect to the parcel development server. Links above.

**Comment by sinclairzx81** [comment]
I am thinking about closing off this issue as its topic is a bit non-descriptive of the some of these follow on discussions. 

FYI, I have just setup a #smoke channel on the freenode IRC servers. You can visit me in there if you wish to have a chat about getting up and running with some of the functionality in the library. As mentioned, getting some help on the project would be appreciated.

Will leave this issue open for a couple of days.

**Comment by Cinemacloud** [comment]
Thank you. Also is there an example of how a remote machine behind a proxy ir on public ip would assimilate as a node?

**Comment by Cinemacloud** [comment]
Can you send my the #smoke transcript to peter.herz at gmail. Also let's continue chat this evening Pacific standard time.

**Comment by sinclairzx81** [comment]
Will close off this issue, have created [this](https://github.com/sinclairzx81/smoke/issues/5) issue in its place which ill follow up on when i get some time to dive into things.

Many Thanks!
